"""Print a live Method A/B/C comparison for one real dashboard request."""

from __future__ import annotations

import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ui.cohort_prompts import build_dashboard_prompt

from privacy.llm_soft_gating_model import FEATURE_NAMES
from privacy.method_a_fixed_4d_router import route_with_method_a_fixed_4d
from privacy.llm_method_b_4d_router import route_with_method_b_4d_soft_gating
from privacy.prism_router import get_active_prism_gater_path, prism_route


def feature_dict(features):
    if features is None:
        return None
    return {
        name: round(float(value), 4)
        for name, value in zip(FEATURE_NAMES, features)
    }


def probability_dict(probabilities):
    if probabilities is None:
        return None
    return {
        name: round(float(value), 4)
        for name, value in probabilities.items()
    }


def main() -> int:
    # This is the real Table 1 request generated by the frontend.
    prompt = build_dashboard_prompt(
        "table1",
        "athletes aged 20 and above",
    )

    print("=" * 80)
    print("REAL PROJECT REQUEST")
    print("=" * 80)
    print(prompt)

    print("\nActive Soft Gating checkpoint:")
    print(get_active_prism_gater_path())

    print("\n" + "=" * 80)
    print("METHOD A: Fixed 4D Rules + Soft Gating")
    print("=" * 80)

    method_a = route_with_method_a_fixed_4d(prompt)

    print("4D Features:")
    print(feature_dict(method_a.features))
    print("Soft Gating Probabilities:")
    print(probability_dict(method_a.probabilities))
    print("Hard Blocked:")
    print(method_a.hard_blocked)
    print("Final Route:")
    print(method_a.route)

    print("\n" + "=" * 80)
    print("METHOD B: Minimal LLM 4D + Soft Gating")
    print("=" * 80)

    method_b = route_with_method_b_4d_soft_gating(prompt)

    print("Success:")
    print(method_b.success)
    if method_b.success:
        print("4D Features:")
        print(feature_dict(method_b.features))
        print("Soft Gating Probabilities:")
        print(probability_dict(method_b.probabilities))
        print("Assessment Cache Used:")
        print(method_b.assessment_cache_used)
        print("Final Route:")
        print(method_b.route)
    else:
        print("ERROR:")
        print(method_b.error)

    print("\n" + "=" * 80)
    print("METHOD C: Detailed Privacy Prompt + Soft Gating")
    print("=" * 80)

    method_c = prism_route(prompt)

    print("Privacy Assessment:")
    print(method_c.llm_privacy_assessment)
    print("4D Features:")
    print(feature_dict(method_c.gating_features))
    print("Soft Gating Probabilities:")
    print(probability_dict(method_c.probabilities))
    print("Blocked:")
    print(method_c.blocked)
    print("Assessment Cache Used:")
    print(method_c.privacy_assessment_cache_used)
    print("Final Route:")
    print(method_c.route)

    print("\n" + "=" * 80)
    print("FINAL COMPARISON")
    print("=" * 80)
    print(f"Method A -> {method_a.route}")
    print(f"Method B -> {method_b.route}" if method_b.success else "Method B -> ERROR")
    print(f"Method C -> {method_c.route}")
    return 0 if method_b.success else 1


if __name__ == "__main__":
    raise SystemExit(main())
